"""
Battle routes - LLM battle API endpoints
"""

import asyncio
import json

from fastapi import APIRouter, BackgroundTasks, HTTPException
from fastapi.responses import StreamingResponse

from ..models.battle import BattleRequest, BattleResponse, BattleStatus
from ..services.battle_service import BattleService
from ..services.surprise_service import SurpriseService

router = APIRouter(prefix="/api/battle", tags=["battle"])

battle_service = BattleService()
surprise_service = SurpriseService()


@router.get("/surprise")
async def get_surprise_config() -> dict:
    """
    Generate a random battle configuration using LLM.
    
    Returns a creative topic and 3 personas:
    - OpenAI: Mischievous troublemaker type
    - Claude: Polite peacemaker type  
    - Grok: Wildcard (anything creative!)
    """
    return await surprise_service.generate_surprise()


@router.post("/", response_model=BattleResponse)
async def create_battle(request: BattleRequest) -> BattleResponse:
    """
    Create a new battle between 3 LLMs.

    This creates the battle but doesn't start it.
    Use /api/battle/{id}/start to begin the battle.
    """
    if len(request.llms) != 3:
        raise HTTPException(
            status_code=400,
            detail="Exactly 3 LLMs are required for a battle",
        )

    state = battle_service.create_battle(request)
    return battle_service.get_battle_response(state)


@router.get("/", response_model=list[BattleResponse])
async def get_all_battles() -> list[BattleResponse]:
    """Get all battles"""
    return battle_service.get_all_battles()


@router.post("/{battle_id}/start", response_model=BattleResponse)
async def start_battle(
    battle_id: str,
    background_tasks: BackgroundTasks,
) -> BattleResponse:
    """
    Start a battle (runs in background).

    Poll /api/battle/{id} to get updates.
    """
    state = battle_service.get_battle(battle_id)
    if not state:
        raise HTTPException(status_code=404, detail="Battle not found")

    if state.status != BattleStatus.PENDING:
        raise HTTPException(
            status_code=400,
            detail=f"Battle already {state.status.value}",
        )

    background_tasks.add_task(battle_service.run_battle, battle_id)
    state.status = BattleStatus.IN_PROGRESS

    return battle_service.get_battle_response(state)


@router.post("/{battle_id}/run", response_model=BattleResponse)
async def run_battle_sync(battle_id: str) -> BattleResponse:
    """
    Run a battle synchronously (waits for completion).

    Use this for simpler clients that don't need streaming.
    """
    state = battle_service.get_battle(battle_id)
    if not state:
        raise HTTPException(status_code=404, detail="Battle not found")

    if state.status != BattleStatus.PENDING:
        raise HTTPException(
            status_code=400,
            detail=f"Battle already {state.status.value}",
        )

    await battle_service.run_battle(battle_id)
    return battle_service.get_battle_response(state)


@router.get("/{battle_id}/stream")
async def stream_battle(battle_id: str) -> StreamingResponse:
    """
    Stream battle messages as Server-Sent Events (SSE).

    Each message is sent as it's generated by the LLMs.
    """
    state = battle_service.get_battle(battle_id)
    if not state:
        raise HTTPException(status_code=404, detail="Battle not found")

    if state.status != BattleStatus.PENDING:
        raise HTTPException(
            status_code=400,
            detail=f"Battle already {state.status.value}",
        )

    async def event_generator():
        try:
            async for message in battle_service.run_battle_streaming(battle_id):
                data = json.dumps(message.model_dump())
                yield f"data: {data}\n\n"
                await asyncio.sleep(0.01)

            yield f"data: {json.dumps({'type': 'complete'})}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
        },
    )


@router.get("/{battle_id}", response_model=BattleResponse)
async def get_battle(battle_id: str) -> BattleResponse:
    """Get current battle state"""
    state = battle_service.get_battle(battle_id)
    if not state:
        raise HTTPException(status_code=404, detail="Battle not found")

    return battle_service.get_battle_response(state)
