export const sampleProblems = [
  {
    id: 1,
    name: 'Two Sum',
    link: 'https://leetcode.com/problems/two-sum/',
    difficulty: 'Easy',
    itemType: 'DSA',
    topic: 'Array',
    company: 'Google',
    confidence: 0,
    status: 'not-started',
    attempts: 0,
    lastSolved: null,
    nextReview: null,
    created: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'React Hooks Deep Dive',
    link: 'https://react.dev/reference/react',
    difficulty: 'Medium',
    itemType: 'Concept',
    topic: 'React',
    company: 'Facebook',
    confidence: 0,
    status: 'not-started',
    attempts: 0,
    lastSolved: null,
    nextReview: null,
    created: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'System Design Primer',
    link: 'https://github.com/donnemartin/system-design-primer',
    difficulty: 'Hard',
    itemType: 'Article',
    topic: 'System Design',
    company: '',
    confidence: 0,
    status: 'not-started',
    attempts: 0,
    lastSolved: null,
    nextReview: null,
    created: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'CSS Grid Layout',
    link: 'https://www.greatfrontend.com/questions/css/grid-layout',
    difficulty: 'Medium',
    itemType: 'Frontend',
    topic: 'CSS',
    company: 'Airbnb',
    confidence: 0,
    status: 'not-started',
    attempts: 0,
    lastSolved: null,
    nextReview: null,
    created: new Date().toISOString(),
  },
];
